/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as ForgotRouteImport } from './pages/forgot'
import { Route as publicLayoutRouteImport } from './pages/(public)/layout'
import { Route as privateLayoutRouteImport } from './pages/(private)/layout'
import { Route as IndexRouteImport } from './pages/index'
import { Route as publicSignUpRouteImport } from './pages/(public)/sign-up'
import { Route as publicSignInRouteImport } from './pages/(public)/sign-in'
import { Route as privateToDoRouteImport } from './pages/(private)/to-do'
import { Route as privateSearchRouteImport } from './pages/(private)/search'
import { Route as privateDashboardRouteImport } from './pages/(private)/dashboard'
import { Route as privateOrgSlugAnimalsRouteImport } from './pages/(private)/org/$slug/animals'

const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLayoutRoute = publicLayoutRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateLayoutRoute = privateLayoutRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSignUpRoute = publicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => publicLayoutRoute,
} as any)
const publicSignInRoute = publicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => publicLayoutRoute,
} as any)
const privateToDoRoute = privateToDoRouteImport.update({
  id: '/to-do',
  path: '/to-do',
  getParentRoute: () => privateLayoutRoute,
} as any)
const privateSearchRoute = privateSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => privateLayoutRoute,
} as any)
const privateDashboardRoute = privateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => privateLayoutRoute,
} as any)
const privateOrgSlugAnimalsRoute = privateOrgSlugAnimalsRouteImport.update({
  id: '/org/$slug/animals',
  path: '/org/$slug/animals',
  getParentRoute: () => privateLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/dashboard': typeof privateDashboardRoute
  '/search': typeof privateSearchRoute
  '/to-do': typeof privateToDoRoute
  '/sign-in': typeof publicSignInRoute
  '/sign-up': typeof publicSignUpRoute
  '/org/$slug/animals': typeof privateOrgSlugAnimalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/dashboard': typeof privateDashboardRoute
  '/search': typeof privateSearchRoute
  '/to-do': typeof privateToDoRoute
  '/sign-in': typeof publicSignInRoute
  '/sign-up': typeof publicSignUpRoute
  '/org/$slug/animals': typeof privateOrgSlugAnimalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(private)': typeof privateLayoutRouteWithChildren
  '/(public)': typeof publicLayoutRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/(private)/dashboard': typeof privateDashboardRoute
  '/(private)/search': typeof privateSearchRoute
  '/(private)/to-do': typeof privateToDoRoute
  '/(public)/sign-in': typeof publicSignInRoute
  '/(public)/sign-up': typeof publicSignUpRoute
  '/(private)/org/$slug/animals': typeof privateOrgSlugAnimalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot'
    | '/dashboard'
    | '/search'
    | '/to-do'
    | '/sign-in'
    | '/sign-up'
    | '/org/$slug/animals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot'
    | '/dashboard'
    | '/search'
    | '/to-do'
    | '/sign-in'
    | '/sign-up'
    | '/org/$slug/animals'
  id:
    | '__root__'
    | '/'
    | '/(private)'
    | '/(public)'
    | '/forgot'
    | '/(private)/dashboard'
    | '/(private)/search'
    | '/(private)/to-do'
    | '/(public)/sign-in'
    | '/(public)/sign-up'
    | '/(private)/org/$slug/animals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  privateLayoutRoute: typeof privateLayoutRouteWithChildren
  publicLayoutRoute: typeof publicLayoutRouteWithChildren
  ForgotRoute: typeof ForgotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/sign-up': {
      id: '/(public)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof publicSignUpRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(public)/sign-in': {
      id: '/(public)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof publicSignInRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(private)/to-do': {
      id: '/(private)/to-do'
      path: '/to-do'
      fullPath: '/to-do'
      preLoaderRoute: typeof privateToDoRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/search': {
      id: '/(private)/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof privateSearchRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/dashboard': {
      id: '/(private)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof privateDashboardRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/org/$slug/animals': {
      id: '/(private)/org/$slug/animals'
      path: '/org/$slug/animals'
      fullPath: '/org/$slug/animals'
      preLoaderRoute: typeof privateOrgSlugAnimalsRouteImport
      parentRoute: typeof privateLayoutRoute
    }
  }
}

interface privateLayoutRouteChildren {
  privateDashboardRoute: typeof privateDashboardRoute
  privateSearchRoute: typeof privateSearchRoute
  privateToDoRoute: typeof privateToDoRoute
  privateOrgSlugAnimalsRoute: typeof privateOrgSlugAnimalsRoute
}

const privateLayoutRouteChildren: privateLayoutRouteChildren = {
  privateDashboardRoute: privateDashboardRoute,
  privateSearchRoute: privateSearchRoute,
  privateToDoRoute: privateToDoRoute,
  privateOrgSlugAnimalsRoute: privateOrgSlugAnimalsRoute,
}

const privateLayoutRouteWithChildren = privateLayoutRoute._addFileChildren(
  privateLayoutRouteChildren,
)

interface publicLayoutRouteChildren {
  publicSignInRoute: typeof publicSignInRoute
  publicSignUpRoute: typeof publicSignUpRoute
}

const publicLayoutRouteChildren: publicLayoutRouteChildren = {
  publicSignInRoute: publicSignInRoute,
  publicSignUpRoute: publicSignUpRoute,
}

const publicLayoutRouteWithChildren = publicLayoutRoute._addFileChildren(
  publicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  privateLayoutRoute: privateLayoutRouteWithChildren,
  publicLayoutRoute: publicLayoutRouteWithChildren,
  ForgotRoute: ForgotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
