/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './pages/__root'
import { Route as ForgotRouteImport } from './pages/forgot'
import { Route as PublicLayoutRouteImport } from './pages/_public/layout'
import { Route as PrivateLayoutRouteImport } from './pages/_private/layout'
import { Route as IndexRouteImport } from './pages/index'
import { Route as PublicSignUpRouteImport } from './pages/_public/sign-up'
import { Route as PublicSignInRouteImport } from './pages/_public/sign-in'
import { Route as PrivateSearchRouteImport } from './pages/_private/search'
import { Route as PrivateDashboardRouteImport } from './pages/_private/dashboard'
import { Route as PrivateOrgSlugAnimalsRouteImport } from './pages/_private/org/$slug/animals'

const PrivateSettingsLazyRouteImport = createFileRoute('/_private/settings')()

const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateLayoutRoute = PrivateLayoutRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateSettingsLazyRoute = PrivateSettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PrivateLayoutRoute,
} as any).lazy(() =>
  import('./pages/_private/settings.lazy').then((d) => d.Route),
)
const PublicSignUpRoute = PublicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicSignInRoute = PublicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PrivateSearchRoute = PrivateSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateDashboardRoute = PrivateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateOrgSlugAnimalsRoute = PrivateOrgSlugAnimalsRouteImport.update({
  id: '/org/$slug/animals',
  path: '/org/$slug/animals',
  getParentRoute: () => PrivateLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/search': typeof PrivateSearchRoute
  '/sign-in': typeof PublicSignInRoute
  '/sign-up': typeof PublicSignUpRoute
  '/settings': typeof PrivateSettingsLazyRoute
  '/org/$slug/animals': typeof PrivateOrgSlugAnimalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot': typeof ForgotRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/search': typeof PrivateSearchRoute
  '/sign-in': typeof PublicSignInRoute
  '/sign-up': typeof PublicSignUpRoute
  '/settings': typeof PrivateSettingsLazyRoute
  '/org/$slug/animals': typeof PrivateOrgSlugAnimalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_private': typeof PrivateLayoutRouteWithChildren
  '/_public': typeof PublicLayoutRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/_private/dashboard': typeof PrivateDashboardRoute
  '/_private/search': typeof PrivateSearchRoute
  '/_public/sign-in': typeof PublicSignInRoute
  '/_public/sign-up': typeof PublicSignUpRoute
  '/_private/settings': typeof PrivateSettingsLazyRoute
  '/_private/org/$slug/animals': typeof PrivateOrgSlugAnimalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot'
    | '/dashboard'
    | '/search'
    | '/sign-in'
    | '/sign-up'
    | '/settings'
    | '/org/$slug/animals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot'
    | '/dashboard'
    | '/search'
    | '/sign-in'
    | '/sign-up'
    | '/settings'
    | '/org/$slug/animals'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/_public'
    | '/forgot'
    | '/_private/dashboard'
    | '/_private/search'
    | '/_public/sign-in'
    | '/_public/sign-up'
    | '/_private/settings'
    | '/_private/org/$slug/animals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateLayoutRoute: typeof PrivateLayoutRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  ForgotRoute: typeof ForgotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/settings': {
      id: '/_private/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PrivateSettingsLazyRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_public/sign-up': {
      id: '/_public/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof PublicSignUpRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/sign-in': {
      id: '/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof PublicSignInRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_private/search': {
      id: '/_private/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PrivateSearchRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/dashboard': {
      id: '/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/org/$slug/animals': {
      id: '/_private/org/$slug/animals'
      path: '/org/$slug/animals'
      fullPath: '/org/$slug/animals'
      preLoaderRoute: typeof PrivateOrgSlugAnimalsRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
  }
}

interface PrivateLayoutRouteChildren {
  PrivateDashboardRoute: typeof PrivateDashboardRoute
  PrivateSearchRoute: typeof PrivateSearchRoute
  PrivateSettingsLazyRoute: typeof PrivateSettingsLazyRoute
  PrivateOrgSlugAnimalsRoute: typeof PrivateOrgSlugAnimalsRoute
}

const PrivateLayoutRouteChildren: PrivateLayoutRouteChildren = {
  PrivateDashboardRoute: PrivateDashboardRoute,
  PrivateSearchRoute: PrivateSearchRoute,
  PrivateSettingsLazyRoute: PrivateSettingsLazyRoute,
  PrivateOrgSlugAnimalsRoute: PrivateOrgSlugAnimalsRoute,
}

const PrivateLayoutRouteWithChildren = PrivateLayoutRoute._addFileChildren(
  PrivateLayoutRouteChildren,
)

interface PublicLayoutRouteChildren {
  PublicSignInRoute: typeof PublicSignInRoute
  PublicSignUpRoute: typeof PublicSignUpRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicSignInRoute: PublicSignInRoute,
  PublicSignUpRoute: PublicSignUpRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateLayoutRoute: PrivateLayoutRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  ForgotRoute: ForgotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
